name: Publish package

on:
  push:
    branches:
      - master

jobs:
  release:
    name:  release
    runs-on: ubuntu-latest
    steps:
      - name:  checkout
        uses: actions/checkout@v2.1.1
      - run: |
          # Obtener la versi贸n actual del package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          # Obtener la versi贸n anterior del package.json desde el commit anterior
          PREVIOUS_VERSION=$(git show HEAD^:package.json | node -p "JSON.parse(require('fs').readFileSync(0, 'utf-8')).version")

          # Comparar las versiones
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "La versi贸n del package.json ha cambiado. Ejecutando acciones..."
            # Resto de tus pasos de acci贸n aqu铆
            npm install
            npm run build
            npm publish --access public
          else
            echo "La versi贸n del package.json no ha cambiado. No se ejecutan acciones."
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
